openapi: "3.0.3"
info:
  title: "MicroServices API"
  description: "MicroServices API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8081"
paths:
  /api/crm/leads:
    post:
      summary: "POST api/crm/leads"
      operationId: "createLead"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LeadDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
  /api/crm/leads/{id}:
    get:
      summary: "GET api/crm/leads/{id}"
      operationId: "getLeadById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
components:
  schemas:
    Campaign:
      type: "object"
      properties:
        name:
          type: "string"
        location:
          type: "string"
    LeadDTO:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        sourceCampaigns:
          type: "array"
          items:
            $ref: "#/components/schemas/Campaign"
    Response:
      type: "object"
      properties: { }